language: ruby
rvm:
  - "2.1.2"

env: TEST_ENV=travis

addons:
  postgresql: "9.3"

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database sendero_test;' -U postgres
  - cp config/database.example.yml config/database.yml; cp config/secrets.example.yml config/secrets.yml
script: bundle exec rspec spec
bundler_args: --without production