# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63ba50f55431314cfe58d09f604efd91f3363e4819d1eb945972d48b5be7206338e6705b5573bfa39da233683151d60c6f4a4e92238fdeadd274ae06e84860a9

test:
  secret_key_base: e5ca32e08a9c188e7ee138590a3a1b9c0808388d228694843eb1c6601293ed2cce454c6c87905fe321c42638531ecfd514f240897507247750580fdb9040592b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
