defaults:
  gmail_address: "masonbuilt246@gmail.com"
  gmail_password: ""
  twitter_account: "masonbuilt"
  twitter_password:
  amazon_account: "michael@masonbuilt.com"
  amazon_password: ""
  amazon_bucket: ""
  amazon_access_key_id: ""
  amazon_secret_access_key: ""
